version: '3'
services:
  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: $SERVICE_NAME
    working_dir: $PWD
    command: /sbin/init
    depends_on:
      riakdb:
        condition: service_healthy
      kds:
        condition: service_healthy
      postgres:
        condition: service_healthy

  riakdb:
    image: docker.io/basho/riak-kv:${RIAK_VERSION}
    environment:
      - CLUSTER_NAME=riakkv
    volumes:
      - ./test/riak/user.conf:/etc/riak/user.conf:ro
    healthcheck:
      test: "riak-admin test"
      interval: 5s
      timeout: 10s
      retries: 20
  member:
    image: docker.io/basho/riak-kv:${RIAK_VERSION}
    links:
      - riakdb
    depends_on:
      - riakdb
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=riakdb
    volumes:
      - ./test/riak/user.conf:/etc/riak/user.conf:ro

  kds:
    image: ghcr.io/valitydev/kds:sha-f034482
    command: /opt/kds/bin/kds foreground
    volumes:
      - ./test/kds/sys.config:/opt/kds/releases/0.1.0/sys.config:ro
      - ./test/kds/ca.crt:/var/lib/kds/ca.crt:ro
      - ./test/kds/server.pem:/var/lib/kds/server.pem:ro
    healthcheck:
      test: "/opt/kds/bin/kds ping"
      interval: 5s
      timeout: 1s
      retries: 20

  postgres:
    image: postgres:15-bookworm
    #command: -c 'max_connections=300'
    environment:
      POSTGRES_DB: "cds"
      POSTGRES_USER: "cds"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U progressor -d progressor_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
