name: Build Docker image

on:
  push:
    branches:
      - 'master'
      - 'epic/**'
  pull_request:
    branches: ['**']

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v2.0.0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Update environment variables
        run: grep -v '^#' .env >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construct tags / labels for an image
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: type=sha

      - name: Build Docker image
        if: github.event_name != 'push'
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          build-args: |
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            OTP_VERSION=${{ env.OTP_VERSION }}
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}

      - name: Build and push multiarch Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            OTP_VERSION=${{ env.OTP_VERSION }}
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}
